on: push
name: Build and Generate Android Apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
         repository: vonProteus/xamarin-android-docker
         path: xamarin-android-docker
      - name: Update Base Image
        run: |
          docker build -t vonproteus/xamarin-android-docker xamarin-android-docker
      - uses: actions/checkout@v2
        with:
         repository: ChristopherHX/Xamarin-Droid-Builder
         path: xamarin-android-docker-action
      - name: Building APK
        uses: ./xamarin-android-docker-action
        with:
          args: /r:True /t:SignAndroidPackage /p:AndroidSdkDirectory=/android/sdk PKHeX.Android/PKHeX.Android.csproj
      - name: Artifacts
        run: |
          mkdir -p apks
          cp PKHeX.Android/PKHeX.Android.csproj/bin/Debug/*.apk apks
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: apks
          path: apks
